apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingestion-output
  namespace: redhat-ods-applications
  labels:
    app: data-ingestion-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
